- name: Debug переменных
  debug:
    msg:
      PROJECT: "{{ PROJECT }}"
      backup_dir: "{{ backup_dir }}"

- name: Проверяем, что playbook выполняется от root
  assert:
    that: ansible_become_user == 'root'
    fail_msg: "Запусти playbook от root или с правами sudo!"

- name: Создаём пользователя проекта
  ansible.builtin.user:
    name: "{{ PROJECT }}"
    state: present
    create_home: true
    groups: ""
    append: false

- name: Создаём каталог резервных копий
  ansible.builtin.file:
    path: "{{ backup_dir }}{{ PROJECT }}"
    state: directory
    owner: "{{ PROJECT }}"
    group: "{{ PROJECT }}"
    mode: "0700"
    recurse: true

- name: Проверяем или создаём SSH-ключ сервера (id_ed25519)
  ansible.builtin.openssh_keypair:
    path: "/root/.ssh/id_ed25519"
    type: ed25519
    comment: "borg"
    force: no
  register: server_key

- name: Показываем публичный ключ сервера (для добавления на клиент)
  ansible.builtin.debug:
    msg: "{{ server_key.public_key }}"

- name: Создаём каталог .ssh для пользователя
  ansible.builtin.file:
    path: "/home/{{ PROJECT }}/.ssh"
    state: directory
    owner: "{{ PROJECT }}"
    group: "{{ PROJECT }}"
    mode: "0750"

- name: Создаём клиентский SSH-ключ id_ed25519
  ansible.builtin.openssh_keypair:
    path: "/home/{{ PROJECT }}/.ssh/id_ed25519"
    type: ed25519
    comment: "borg_client"
    owner: "{{ PROJECT }}"
    group: "{{ PROJECT }}"
    mode: "0600"
  register: client_key

- name: Настраиваем authorized_keys для пользователя
  ansible.builtin.copy:
    dest: "/home/{{ PROJECT }}/.ssh/authorized_keys"
    content: "{{ client_key.public_key }}"
    owner: "{{ PROJECT }}"
    group: "{{ PROJECT }}"
    mode: "0600"

- name: Перезапускаем sshd
  ansible.builtin.service:
    name: sshd
    state: restarted

- name: Инициализируем borg-репозиторий (если не существует)
  ansible.builtin.command:
    cmd: "borg init --encryption=repokey {{ backup_dir }}{{ PROJECT }}"
    creates: "{{ backup_dir }}{{ PROJECT }}/config"

- name: Создаём каталог проекта borg
  ansible.builtin.file:
    path: "/root/.borg/projects/{{ PROJECT }}"
    state: directory
    mode: "0700"

- name: Создаём full.yaml из шаблона
  ansible.builtin.template:
    src: full.yaml.j2
    dest: "/root/.borg/projects/{{ PROJECT }}/full.yaml"
    mode: "0600"

- name: Создаём settings.conf (если отсутствует)
  ansible.builtin.template:
    src: settings.conf.example
    dest: "/root/.borg/projects/{{ PROJECT }}/settings.conf"
    mode: "0600"
