- name: Проверяем, что выполняется от root
  assert:
    that: ansible_user_id == 'root'
    fail_msg: "Запусти playbook от root!"

- name: Создаём пользователя по проекту
  ansible.builtin.user:
    name: "{{ PROJECT }}"
    state: present
    create_home: true

- name: Удаляем пользователя из группы users (если есть)
  ansible.builtin.command: "deluser {{ PROJECT }} users"
  ignore_errors: true

- name: Создаём каталог резервных копий
  ansible.builtin.file:
    path: "{{ backup_dir }}{{ PROJECT }}"
    state: directory
    owner: "{{ PROJECT }}"
    group: "{{ PROJECT }}"
    mode: "0700"
    recurse: true

- name: Проверяем или создаём SSH-ключ сервера (id_ed25519)
  ansible.builtin.openssh_keypair:
    path: "/root/.ssh/id_ed25519"
    type: ed25519
    comment: "borg"
  register: server_key

- name: Показываем публичный ключ сервера (для добавления на клиент)
  debug:
    msg: "{{ server_key.public_key }}"

- name: Проверяем или создаём SSH-ключ клиента
  ansible.builtin.file:
    path: "/home/{{ PROJECT }}/.ssh"
    state: directory
    owner: "{{ PROJECT }}"
    group: "{{ PROJECT }}"
    mode: "0750"

- name: Создаём клиентский ключ id_ed25519
  ansible.builtin.openssh_keypair:
    path: "/home/{{ PROJECT }}/.ssh/id_ed25519"
    type: ed25519
    comment: "borg_client"
    owner: "{{ PROJECT }}"
    group: "{{ PROJECT }}"
    mode: "0600"
  register: client_key

- name: Настраиваем authorized_keys
  ansible.builtin.copy:
    dest: "/home/{{ username }}/.ssh/authorized_keys"
    content: "{{ client_key.public_key }}"
    owner: root
    group: "{{ PROJECT }}"
    mode: "0640"

- name: Перезапускаем sshd
  ansible.builtin.service:
    name: sshd
    state: restarted

- name: Проверяем, инициализирован ли borg-репозиторий
  ansible.builtin.command: "borg list {{ backup_dir }}{{ PROJECT }}"
  register: borg_check
  failed_when: false

- name: Инициализируем borg-репозиторий (если не существует)
  ansible.builtin.command: "borg init --encryption=repokey {{ backup_dir }}{{ PROJECT }}"
  when: borg_check.rc != 0

- name: Создаём каталог проекта borg
  ansible.builtin.file:
    path: "/root/.borg/projects/{{ PROJECT }}"
    state: directory
    mode: "0700"

- name: Создаём full.yaml
  ansible.builtin.template:
    src: full.yaml.j2
    dest: "/root/.borg/projects/{{ PROJECT }}/full.yaml"
    mode: "0600"

- name: Создаём settings.conf (если отсутствует)
  ansible.builtin.template:
    src: settings.conf.example
    dest: "/root/.borg/projects/{{ PROJECT }}/settings.conf"
    mode: "0600"
